# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# ruff: noqa
# pyright: reportAttributeAccessIssue=false
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ganker.rpc.v1 import proxy_pb2 as ganker_dot_rpc_dot_v1_dot_proxy__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ganker/rpc/v1/proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GankerProxyStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTrainingRun = channel.unary_unary(
                '/ganker.v1.GankerProxy/CreateTrainingRun',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.CreateTrainingRunRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.CreateTrainingRunResponse.FromString,
                _registered_method=True)
        self.ForwardBackward = channel.unary_unary(
                '/ganker.v1.GankerProxy/ForwardBackward',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.ForwardBackwardRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.ForwardBackwardResponse.FromString,
                _registered_method=True)
        self.OptimStep = channel.unary_unary(
                '/ganker.v1.GankerProxy/OptimStep',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.OptimStepRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.OptimStepResponse.FromString,
                _registered_method=True)
        self.SaveWeights = channel.unary_unary(
                '/ganker.v1.GankerProxy/SaveWeights',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SaveWeightsRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SaveWeightsResponse.FromString,
                _registered_method=True)
        self.RefreshWeights = channel.unary_unary(
                '/ganker.v1.GankerProxy/RefreshWeights',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.RefreshWeightsRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.RefreshWeightsResponse.FromString,
                _registered_method=True)
        self.Sample = channel.unary_unary(
                '/ganker.v1.GankerProxy/Sample',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SampleRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SampleResponse.FromString,
                _registered_method=True)
        self.GetTelemetrySummary = channel.unary_unary(
                '/ganker.v1.GankerProxy/GetTelemetrySummary',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.GetTelemetrySummaryRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.GetTelemetrySummaryResponse.FromString,
                _registered_method=True)
        self.DownloadArtifactFile = channel.unary_unary(
                '/ganker.v1.GankerProxy/DownloadArtifactFile',
                request_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.DownloadArtifactFileRequest.SerializeToString,
                response_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.DownloadArtifactFileResponse.FromString,
                _registered_method=True)


class GankerProxyServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTrainingRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardBackward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetrySummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadArtifactFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GankerProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTrainingRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTrainingRun,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.CreateTrainingRunRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.CreateTrainingRunResponse.SerializeToString,
            ),
            'ForwardBackward': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardBackward,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.ForwardBackwardRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.ForwardBackwardResponse.SerializeToString,
            ),
            'OptimStep': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimStep,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.OptimStepRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.OptimStepResponse.SerializeToString,
            ),
            'SaveWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveWeights,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SaveWeightsRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SaveWeightsResponse.SerializeToString,
            ),
            'RefreshWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshWeights,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.RefreshWeightsRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.RefreshWeightsResponse.SerializeToString,
            ),
            'Sample': grpc.unary_unary_rpc_method_handler(
                    servicer.Sample,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SampleRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.SampleResponse.SerializeToString,
            ),
            'GetTelemetrySummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetrySummary,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.GetTelemetrySummaryRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.GetTelemetrySummaryResponse.SerializeToString,
            ),
            'DownloadArtifactFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadArtifactFile,
                    request_deserializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.DownloadArtifactFileRequest.FromString,
                    response_serializer=ganker_dot_rpc_dot_v1_dot_proxy__pb2.DownloadArtifactFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ganker.v1.GankerProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ganker.v1.GankerProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GankerProxy:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTrainingRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/CreateTrainingRun',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.CreateTrainingRunRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.CreateTrainingRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardBackward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/ForwardBackward',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.ForwardBackwardRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.ForwardBackwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/OptimStep',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.OptimStepRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.OptimStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/SaveWeights',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.SaveWeightsRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.SaveWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/RefreshWeights',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.RefreshWeightsRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.RefreshWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/Sample',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.SampleRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.SampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetrySummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/GetTelemetrySummary',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.GetTelemetrySummaryRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.GetTelemetrySummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadArtifactFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ganker.v1.GankerProxy/DownloadArtifactFile',
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.DownloadArtifactFileRequest.SerializeToString,
            ganker_dot_rpc_dot_v1_dot_proxy__pb2.DownloadArtifactFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
